services:
  - type: web
    name: app
    env: node
    region: oregon
    plan: free
    buildCommand: "npm ci && npm run build"
    startCommand: "npm ci --production && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
